# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b57db893eae5f7f0b8fb4876f4a8797e783b453f33a97ceae24d7640bd1314fdf2ded4a96244c7c071fd6da50f4d4bd9ffb42e3cfae932e1ad1b862aed32de76

test:
  secret_key_base: 6d271c88e3eb202e6a62934d69aa3bf2adffbc6e5c3b0463f38da6090ac4f963ddbdd5951967806748a312bd0966d3d90a86697ae7eaa86b9de2f2a216381676

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
